SRC = \
  src/constants.f90 \
  src/string.f90 \
  src/utils/meta_data_utils.f90 \
  src/MPI.f90 \
  src/base_io/file_handle.f90 \
  src/base_io/qmcfort_io.f90 \
  src/base_io/log_manager.f90 \
  src/base_io/array_file_io/array_file_io.f90 \
  src/base_io/array_file_io/array_txt_file_io.f90 \
  src/base_io/array_file_io/array_bin_file_io.f90 \
  src/base_io/array_file_io/array_numpy_file_io.f90 \
  src/base_io/array_file_io/array_file_io_factories.f90 \
  src/qmcfort_pos.f90 \
  src/base_io/qmcfort_in.f90 \
  src/method_base.f90 \
  src/profiling.f90 \
  src/stat_analysis.f90 \
  src/growth_est_config.f90 \
  src/growth_est.f90 \
  src/random/rng_utils.f90 \
  src/random/basic_rng/basic_rng.f90 \
  src/random/basic_rng/intrinsic_basic_rng.f90 \
  src/random/basic_rng/lcg32_basic_rng.f90 \
  src/random/basic_rng/lcg48_basic_rng.f90 \
  src/random/basic_rng/lcg64_basic_rng.f90 \
  src/random/basic_rng/vsl_basic_rng.f90 \
  src/random/basic_rng/brng_factories.f90 \
  src/random/dist_rng/dist_rng.f90 \
  src/random/dist_rng/vsl_dist_rng.f90 \
  src/random/dist_rng/drng_factories.f90 \
  src/sparse.f90 \
  src/standalone.f90 \
  src/mc_descriptor.f90 \
  src/statistics.f90 \
  src/LAPACK.f90 \
  src/regression.f90 \
  src/krylov.f90 \
  src/expm/expm_utils.f90 \
  src/expm/expm_exact_mod.f90 \
  src/expm/expm_taylor_mod.f90 \
  src/expm/expm_cheb_mod.f90 \
  src/expm/expm_krylov_mod.f90 \
  src/expm/expm_mod.f90 \
  src/diis/diis_config.f90 \
  src/diis/diis_mixer.f90 \
  src/gto/GAMMA.f90 \
  src/gto/boys_functions.f90 \
  src/energy_types.f90 \
  src/slater.f90 \
  src/slater_condon_rules.f90 \
  src/spin_utils.f90 \
  src/hamilton/hamilton_vars.f90 \
  src/hamilton/hamilton_layout.f90 \
  src/hamilton/hamilton_operations.f90 \
  src/ORTH.f90 \
  src/gto/gauss_base.f90 \
  src/gto/mc_murchie_davidson.f90 \
  src/gto/gauss_integrals.f90 \
  src/hamilton/hamilton_io.f90 \
  src/cholesky.f90 \
  src/nosd.f90 \
  src/hamilton/hamilton_type.f90 \
  src/hamilton/cas_hamilton.f90 \
  src/fcidump.f90 \
  src/wave_trial/wave_trial_des.f90 \
  src/wave_trial/wave_trial.f90 \
  src/wave_trial/wave_trial_sd.f90 \
  src/wave_trial/c_wave_trial_sd.f90 \
  src/wave_trial/wave_trial_cas.f90 \
  src/wave_trial/wave_trial_noci.f90 \
  src/wave_trial/wave_trial_factories.f90 \
  src/CI.f90 \
  src/hfproc.f90 \
  src/frozen_core_approx.f90 \
  src/mp2.f90 \
  src/FCIQMC.f90 \
  src/FCI_WRAP.f90 \
  src/propagators.f90 \
  src/afqmc/afqmc_intags.f90 \
  src/afqmc/afqmc_walker.f90 \
  src/afqmc/afqmc_proj_config.f90 \
  src/afqmc/afqmc_proj.f90 \
  src/afqmc/afqmc_descriptor.f90 \
  src/afqmc/afqmc_importance_sampling.f90 \
  src/afqmc/aux_field_gen.f90 \
  src/afqmc/afqmc_prop_config.f90 \
  src/afqmc/afqmc_prop.f90 \
  src/afqmc/afqmc_energy.f90 \
  src/afqmc/afqmc_rev.f90 \
  src/afqmc/afqmc_rebalance.f90 \
  src/afqmc/afqmc_debug.f90 \
  src/afqmc/afqmc_io.f90 \
  src/afqmc/afqmc_chkpt.f90 \
  src/noci/noci_intags.f90 \
  src/noci/noci_selector_des.f90 \
  src/noci/noci_selector.f90 \
  src/afqmc/afqmc_walker_factories.f90 \
  src/afqmc/afqmc.f90 \
  src/noci/noci_afqmc_selection.f90 \
  src/main.f90


TEST_SRC = \
  tests/unit/fruit/fruit.f90 \
  tests/unit/test_string.f90 \
  tests/unit/base_io/test_file_handle.f90 \
  tests/unit/base_io/array_file_io/test_array_bin_file_io.f90 \
  tests/unit/base_io/array_file_io/test_array_file_io_factories.f90 \
  tests/unit/base_io/array_file_io/test_array_numpy_file_io.f90 \
  tests/unit/base_io/array_file_io/test_array_txt_file_io.f90 \
  tests/unit/test_method_base.f90 \
  tests/unit/test_qmcfort_pos.f90 \
  tests/unit/base_io/test_qmcfort_in.f90 \
  tests/unit/test_mc_descriptor.f90 \
  tests/unit/test_energy_types.f90 \
  tests/unit/random/basic_rng/test_lcg32_basic_rng.f90 \
  tests/unit/random/basic_rng/test_lcg48_basic_rng.f90 \
  tests/unit/random/basic_rng/test_lcg64_basic_rng.f90 \
  tests/unit/random/basic_rng/test_vsl_basic_rng.f90 \
  tests/unit/test_lapack.f90 \
  tests/unit/test_regression.f90 \
  tests/unit/hamilton/test_hamilton_operations.f90 \
  tests/unit/test_krylov.f90 \
  tests/unit/expm/test_expm_cheb_mod.f90 \
  tests/unit/expm/test_expm_krylov_mod.f90 \
  tests/unit/expm/test_expm_mod.f90 \
  tests/unit/expm/test_expm_taylor_mod.f90 \
  tests/unit/test_sparse.f90 \
  tests/unit/test_standalone.f90 \
  tests/unit/test_statistics.f90 \
  tests/unit/diis/test_diis_mixer.f90 \
  tests/unit/gto/test_gauss_base.f90 \
  tests/unit/gto/test_boys_functions.f90 \
  tests/unit/gto/test_mc_murchie_davidson.f90 \
  tests/unit/test_hfproc.f90 \
  tests/unit/test_slater.f90 \
  tests/unit/test_slater_condon_rules.f90 \
  tests/unit/wave_trial/test_wave_trial_md.f90 \
  tests/unit/afqmc/test_afqmc_proj.f90 \
  tests/unit/test_main.f90