# Convenience ==================================================================
.PHONY: help
help:
	@echo "TARGETS:"
	@echo "========"
	@echo "    qmcfort            -    compile QmcFort code"
	@echo "    clean              -    remove compiled QmcFort files"
	@echo ""
	@echo "    ut                 -    compile and run unit tests"
	@echo "    ut-clean           -    remove compiled unit test files"
	@echo ""
	@echo "    distclean          -    remove build directory specified in Makefile"
	@echo "    veryclean          -    remove all build directories"
	@echo ""
	@echo "    rt                 -    run regression tests"
	@echo "    rt-clean           -    remove regression test results"
	@echo "    rt-update          -    update regression test reference values"
	@echo "    rt-list            -    list regression tests"
	@echo ""
	@echo "    venv               -    create python3 virtual environment"
	@echo "    venv-clean         -    remove python3 virtual environment"
	@echo "    venv-all           -    equivalent to venv-bse venv-qmcfortpy"
	@echo "    venv-bse           -    install basis_set_exchange package needed for GTO basis sets"
	@echo "    venv-qmcfortpy     -    Python package to interface QmcFort to other codes (PySCF)"
	@echo ""
	@echo "    basis_sets         -    downloads/updates GTO basis sets specified in tools/update_basis_sets.py"
	@echo ""
	@echo "TOOLCHAIN (<compiler>-<blas_lapack_lib>-<mpi_lib>):"
	@echo "==================================================="
	@echo "    ifort-mkl-intelmpi          (default)"
	@echo "    ifort-mkl-openmpi"
	@echo "    gfortran-openblas-openmpi"
	@echo ""
	@echo "USAGE:"
	@echo "======"
	@echo "    make TOOLCHAIN=ifort-mkl-intelmpi qmcfort"
	@echo "    make DEPS=1 TOOLCHAIN=intel-mkl-openmpi qmcfort -j4"
	@echo "    make DEPS=1 ut -j4"
	@echo "    make rt"
	@echo "    make rt CASES='*afqmc*'"
	@echo "    make rt CASES='h2o_afqmc_vdz c6h6_mp2_fs_sto3g'"
	@echo "    make BS_DIR=data/basis_sets basis_sets"
	@echo "    make VENV_DIR=.venv_hpc venv-all"